### ISSUE TITLE
Update from old powsim

### ISSUE THREAD

**Issue by yonchoi** [bvieth/powsimR#10]
Hi,

I am trying to install the old powsim package, as I am running an another package that is dependent on the older version of powsim, not powsimR. However, I am running into issues with installing NBGOF. I noticed that in the newer version of powsimR, does not use this package anymore. Was there any issues with the package, perhaps with installation by any chance? 

I apologize for posting this on the powsimR page, but I was not sure if the other powsim page was still being maintained. Please let me know if this is an issue, so I can remove the post.

Thank you!

**Comment by bvieth** [comment]
Hello,

indeed the old powsim is no longer maintained. Could you maybe point me to the package that uses powsim(R) functions? I might be able to check what of powsim is used. I excluded NBGOF since I did not need its functions for goodness of fit testing for single cell data. 

With regards to DLL issues during installation, does this now occur while installing powsim or powsimR? Could you maybe send me the error messages as well as the output of sessionInfo()? It is otherwise rather hard to gauge what exactly is the issue.

Kind regards
Beate
