### ISSUE TITLE
Issues installing 

### ISSUE THREAD

**Issue by pelacables** [bvieth/powsimR#15]
I'm trying to install the package after having installed all the depdencies.
the command
```bash
devtools::install_github("bvieth/powsimR", build_vignettes = TRUE, dependencies = FALSE)
```
fails becasue:
```bash
Installing powsimR
svn: E175002: Unable to connect to a repository at URL 'https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/S4Vectors'
svn: E175002: OPTIONS of 'https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/S4Vectors': could not connect to server (https://hedgehog.fhcrc.org)
Installation failed: There was a problem retrieving the current SVN revision
Warning message:
running command ''/bin/svn' info --xml --username readonly --password readonly https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/S4Vectors' had status 1
```

S4Vector is installed in my system an can be loaded:
```bash
> library('S4Vectors')
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’
[....]
```

what is triggering the svn command?

**Comment by pelacables** [comment]
Finally I downloaded the code and installed like:

```bash
> install.packages('../powsimR-master.tar.gz', repos = NULL, type="source")
```
I also had to increase the num of DLLs:

```bash
> Sys.setenv(R_MAX_NUM_DLLS=500)
```

I don't know what's wrong but the Remotes in the DESCRIPTION are not ignored when install_github with dependecies =FALSE.

**Comment by bvieth** [comment]
Hello,

thanks for trying out powsimR and I am sorry that the installation is not working for you. 
I tried to reconstruct your first error without success. It appears to be a svn related issue that I encountered before as well for e.g. BASiCS (a package that was then available on bioconductor for installation via biocLite for the current R version but not listed in the repository).
Since you have all dependencies installed successfully, might I suggest that you increase the ulimit first so that you can set the DLLs to a higher number? It should be possible on your machine. You can find a guide how to do this [here](https://gist.github.com/tombigel/d503800a282fcadbee14b537735d202c).

Kind regards

**Comment by nlawlor** [comment]
Hi bvieth,

Thank you very much for the feedback. This suggestion worked great, I've successfully installed and loaded the package!

Thanks,
Nathan

**Comment by bvieth** [comment]
Dear Nathan,

awesome news! If you need any further assistance, feel free to open another issue.

Beate
