### ISSUE TITLE
Will not install on R 3.5.1

### ISSUE THREAD

**Issue by raivivek** [bvieth/powsimR#36]
Looks like some packages have set R > 3.6.0 as requirement, thus fresh install of `powsimR` does not install on R 3.5.1 anymore.

I believe the problematic packages are `fpc`, `amap`, `rngtools`.

**Comment by bvieth** [comment]
Hello,

I am sorry for the inconvenience. The problem is that I want to include the newest versions of packages, particularly Bioconductor. Given that those packages are quickly changing (function names, settings, dependencies), I have opted to only support the most current R version.

Kind regards
Beate
