### ISSUE TITLE
could not find function "insilicoNBParam"

### ISSUE THREAD

**Issue by taryn0h** [bvieth/powsimR#39]
Hi. I'm trying to do some simulation to calculate power for a single cell RNA-seq study. I'm getting hung up with the in silico parameter simulation function. 

Just running the example I get this:
insilico.singlecell <- insilicoNBParam(means=function(x) rgamma(x, 4, 2),
                                          dispersion=function(x) 2 + 150/x,
                                          dropout=NULL,
                                         sf=function(x) 2^rnorm(n=x, mean=0, sd=0.5),
                                          RNAseq='singlecell')

Error in insilicoNBParam(means = function(x) rgamma(x, 4, 2), dispersion = function(x) 2 +  : 
  could not find function "insilicoNBParam"

**Comment by bvieth** [comment]
Hello,

I have removed this functionality from powsimR since we found that using these dispersion functions for simulations was not really realistic for single cells because the variability was too low.

I would recommend to use a publicly available data set, e.g. from [conquer](http://imlspenticton.uzh.ch:3838/conquer/) or [recount2](https://jhubiostatistics.shinyapps.io/recount/) that resembles the expression data you are interested in and want to do statistical power analysis on.

Kind regards
Beate
