### ISSUE TITLE
devtools remotes for easier installation

### ISSUE THREAD

**Issue by oganm** [bvieth/powsimR#8]
Installation can be simplified by using devtools remote syntax at DESCRIPTION. You just need to list your dependencies and where they come from. Github and bioconductor is easy to set up.

See https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html

Edit: Just noticed the github ones listed as remotes. If bioc ones are also added there won't be a need to run pre-installation commands

**Comment by bvieth** [comment]
Hello,

thank you for pointing this out. I will give it another try. In the past, I ran into some errors because my dependencies would try to install their own dependencies but fail and then throw an error if I set in my install_github command dependencies=T which is the default. That is the reason I separated the two out.
